name: HFGI3D
channels:
  - pytorch3d
  - iopath
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotlipy=0.7.0=py39hb9d737c_1004
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.07.19=h06a4308_0
  - certifi=2022.6.15=pyhd8ed1ab_1
  - cffi=1.14.6=py39he32792d_0
  - colorama=0.4.5=pyhd8ed1ab_0
  - cryptography=37.0.2=py39hd97740a_0
  - cudatoolkit=11.6.0=hecad31d_10
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.10.4=h0708190_1
  - fvcore=0.1.5.post20220512=pyhd8ed1ab_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - idna=3.3=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - iopath=0.1.9=py39
  - jpeg=9e=h166bdaf_1
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.17=h166bdaf_0
  - libpng=1.6.37=h21135ba_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.2.0=hf544144_3
  - libwebp-base=1.2.2=h7f98852_1
  - lz4-c=1.9.3=h9c3ff4c_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7e14d7c_0
  - mkl_fft=1.3.1=py39h0c7bc48_1
  - mkl_random=1.2.2=py39hde0f152_0
  - ncurses=6.3=h5eee18b_3
  - nettle=3.6=he412f7d_0
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1q=h7f8727e_0
  - pip=22.1.2=py39h06a4308_0
  - portalocker=2.5.1=py39hf3d152e_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.12=h12debd9_1
  - python_abi=3.9=2_cp39
  - pytorch=1.12.1=py3.9_cuda11.6_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - pytorch3d=0.7.0=py39_cu116_pyt1121
  - pyyaml=6.0=py39hb9d737c_4
  - readline=8.1.2=h7f8727e_1
  - setuptools=63.4.1=py39h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.39.2=h5082296_0
  - tabulate=0.8.10=pyhd8ed1ab_0
  - termcolor=1.1.0=pyhd8ed1ab_3
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.12.1=py39_cu116
  - torchvision=0.13.1=py39_cu116
  - typing_extensions=4.3.0=pyha770c72_0
  - tzdata=2022a=hda174b7_0
  - urllib3=1.26.11=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - yacs=0.1.8=pyhd8ed1ab_0
  - yaml=0.2.5=h7f98852_2
  - zlib=1.2.12=h7f8727e_2
  - zstd=1.5.0=ha95c52a_0
  - pip:
    - absl-py==1.3.0
    - cachetools==5.2.0
    - charset-normalizer==2.0.12
    - click==8.1.3
    - cycler==0.11.0
    - docker-pycreds==0.4.0
    - gitdb==4.0.10
    - gitpython==3.1.29
    - glfw==2.2.0
    - google-auth==2.14.1
    - google-auth-oauthlib==0.4.6
    - grpcio==1.50.0
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.3
    - imgui==1.3.0
    - importlib-metadata==5.1.0
    - joblib==1.2.0
    - kiwisolver==1.4.4
    - lpips==0.1.4
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.4.2
    - mrcfile==1.4.3
    - ninja==1.10.2
    - numpy==1.22.4
    - oauthlib==3.2.2
    - opencv-python==4.6.0.66
    - pathtools==0.1.2
    - pillow==9.3.0
    - promise==2.3
    - protobuf==3.20.3
    - psutil==5.9.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyopengl==3.1.5
    - pyparsing==3.0.9
    - pyspng==0.1.1
    - python-dateutil==2.8.2
    - requests==2.26.0
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scipy==1.7.1
    - sentry-sdk==1.11.1
    - setproctitle==1.3.2
    - shortuuid==1.0.11
    - smmap==5.0.0
    - tensorboard==2.11.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tqdm==4.62.2
    - trimesh==3.15.3
    - wandb==0.13.5
    - werkzeug==2.2.2
    - zipp==3.11.0

